module.exports = [
  '',
  'about-me',
  'agenda',
  'eleventy-intro',
  'eleventy-config',
  'adding-content',
  'content-metadata',
  'create-layout',
  'partials',
  'eleventy-plugins',
  'own-plugins',
  'basic-bundling',
  'advanced-tooling',
  'css-js-tooling',
  'learning-resources',
  'thank-you',
];
